# The west manifest file for upstream Zephyr.
#
# The per-installation west configuration file, .west/config, sets the
# path to the project containing this file in the [manifest] section's
# "path" variable.
#
# You are free to create your own manifest files and put them in any
# repository you want, to create your own custom Zephyr installations.
# For example, you could create a manifest file in your own out of
# tree application directory, which would pull this zephyr repository
# in as an ordinary project.
#
# You can pass your manifest repositories to west init when creating a
# new Zephyr installation. See the west documentation for more
# information.

manifest:
  defaults:
    remote: upstream

  remotes:
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos
    - name: recogni
      url-base: git@github.com:recogni
    - name: recogni-http
      url-base: https://github.com/recogni

  #
  # Please add items below based on alphabetical order
  projects:
    - name: fatfs
      path: modules/fs/fatfs
    - name: littlefs
      revision: 9e4498d1c73009acd84bb36036ee5e2869112a6c
      path: modules/fs/littlefs
    - name: mbedtls
      revision: d9535d4fa440b0435934e5d19c38c4010fe73e6a
      path: modules/crypto/mbedtls
      remote: recogni-http
    - name: mcuboot
      path: modules/mcuboot
      revision: 8df6c9f4b4ccd2af76bf60d34de06dbd87130343
      remote: recogni-http
    - name: mcumgr
      revision: 9b1ed3cc454d27b82d68010bdc23517a42244f50
      path: modules/lib/mcumgr
      remote: recogni-http
    - name: tinycbor
      revision: 40daca97b478989884bffb5226e9ab73ca54b8c4
      path: modules/lib/tinycbor

    

  self:
    path: zephyr
    west-commands: scripts/west-commands.yml
