title: base device binding

description: >
    Binding for device

properties:
    compatible:
        type: string-array
        required: true
        description: compatible strings

    reg:
        type: array
        description: register space
        required: false

    reg-names:
        type: string-array
        description: name of each register space
        required: false

    interrupts:
        type: array
        required: false
        description: interrupts for device

    interrupt-names:
        type: string-array
        required: false
        description: name of each interrupt

    label:
        type: string
        required: false
        description: Human readable string describing the device (used by Zephyr for API name)

    clocks:
        type: array
        required: false
        description: Clock gate information
