# Copyright (c) 2020 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# Common fields for all services

properties:
    compatible:
        type: string-array
        required: true
        description: compatible strings

    status:
        type: string
        required: true
        description: indicates the operational status of a service
        enum:
           - "okay"
           - "disabled"

    reg:
        type: array
        description: register space
        required: false
