# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

description: |
  Partition or other storage area for application binary image.

compatible: "zephyr,application-image"

include: base.yaml

properties:
  label:
    required: true
  reg:
    required: true
