[package]
name = "adsp_loader"
version = "0.1.0"
edition = "2021"
description = "Intel ADSP firmware loader"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log  = "0.4"
env_logger = "0.9.0"
adsp = {version = "0.1", path = "../adsp" }
