name: Pull Request Assigner

on:
  pull_request_target:
    types:
    - opened
    - synchronize
    - reopened
    - ready_for_review
    branches:
    - main
    - v*-branch

jobs:
  assignment:
    name: Pull Request Assignment
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-22.04
    env:
      COMMIT_RANGE: ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
      BASE_REF: ${{ github.base_ref }}

    steps:
    - name: Install Python dependencies
      run: |
        sudo pip3 install -U setuptools wheel pip
        pip3 install -U PyGithub>=1.55

    - name: Check out source code
      uses: actions/checkout@v3

    - name: Run assignment script
      env:
        GITHUB_TOKEN: ${{ secrets.ZB_GITHUB_TOKEN }}
      run: |
        echo ${COMMIT_RANGE}
        echo ${BASE_REF}
        python3 scripts/set_assignees.py \
          -v \
          -o ${{ github.event.repository.owner.login }} \
          -r ${{ github.event.repository.name }} \
          -M MAINTAINERS.yml \
          -P ${{ github.event.pull_request.number }}
