name: Rebase stable-rebased branch

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  prepare:
    runs-on: self-hosted
    steps:
    - name: clone repo
      run: |
        git clone -b ${{ env.branch }} git@github.com:phytec-labs/${{ env.repository_name }}.git zephyr
      env:
        repository_name: elements-zephyr
        branch: stable-rebased

    - name: rebase to upstream
      run: |
        cd ${{ env.repository_name }}
        git remote add upstream https://github.com/zephyrproject-rtos/zephyr.git
        git fetch upstream
        git rebase upstream/main
        cd ../
      env:
        repository_name: zephyr

  deploy:
    runs-on: self-hosted
    needs: [build]
    steps:
    - name: push back to branch
      run: |
        cd ${{ env.repository_name }}
        git push origin HEAD:${{ env.branch }} -f
        cd ../
      env:
        repository_name: zephyr
        branch: stable-rebased

  cleanup:
    runs-on: self-hosted
    needs: [deploy]
    if: always()
    steps:
    - name: post cleanup
      run: |
        rm -rf .west build venv
      env:
        repository_name: elements-zephyr
