name: Compliance Checks

on: pull_request

jobs:
  maintainer_check:
    runs-on: ubuntu-20.04
    name: Check MAINTAINERS file
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    - name: Run Maintainers Script
      id: maintainer
      env:
        BASE_REF: ${{ github.base_ref }}
      run: |
        ./scripts/ci/ci_compliance.sh maintainer_check

  check_compliance:
    runs-on: ubuntu-20.04
    name: Run compliance checks on patch series (PR)
    steps:
    - name: Update PATH for west
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Checkout the code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: cache-pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-doc-pip

    - name: Install python dependencies
      run: |
        ./scripts/ci/ci_compliance.sh check_compliance python-deps

    - name: west setup
      env:
        BASE_REF: ${{ github.base_ref }}
      run: |
 	./scripts/ci/ci_compliance.sh check_compliance west-setup

    - name: Run Compliance Tests
      continue-on-error: true
      id: compliance
      env:
        BASE_REF: ${{ github.base_ref }}
      run: |
        ./scripts/ci/ci_compliance.sh check_compliance compliance-tests

    - name: upload-results
      uses: actions/upload-artifact@v3
      continue-on-error: True
      with:
        name: compliance.xml
        path: compliance.xml

    - name: check-warns
      run: |
        ./scripts/ci/ci_compliance.sh check_compliance check-warns
